# Generated by Django 4.1.2 on 2026-03-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0001_initial'),
        ('companies', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tow_truck', 'Tow Truck'), ('box_truck', 'Box Truck'), ('dispatcher', 'Dispatcher'), ('shop', 'Shop / Mechanic')], default='tow_truck', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', '1099 / Contract'), ('temp', 'Temporary')], default='full_time', max_length=20)),
                ('cdl_requirement', models.CharField(choices=[('cdl_a', 'CDL-A Required'), ('cdl_b', 'CDL-B Required'), ('no_cdl', 'No CDL Required'), ('cdl_preferred', 'CDL Preferred')], default='no_cdl', max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('pay_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_type', models.CharField(choices=[('hourly', 'Per Hour'), ('per_mile', 'Per Mile'), ('salary', 'Salary'), ('per_load', 'Per Load')], default='hourly', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True, help_text='JSON list of benefits')),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('filled', 'Filled'), ('draft', 'Draft')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pools.citypool')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='companies.companyprofile')),
            ],
            options={
                'ordering': ['-is_urgent', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('hired', 'Hired')], default='applied', max_length=10)),
                ('flagged_by_dispatcher', models.BooleanField(default=False)),
                ('interview_time', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='drivers.driverprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joblisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'driver')},
            },
        ),
    ]
