# Generated by Django 4.1.2 on 2026-03-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobapplication_stage_applicationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('invited', 'Invited'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=10),
        ),
    ]
