# Generated by Django 4.1.2 on 2026-03-17 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('pools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdl_class', models.CharField(choices=[('cdl_a', 'CDL-A'), ('cdl_b', 'CDL-B'), ('no_cdl', 'No CDL')], default='no_cdl', max_length=10)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('specialties', models.CharField(blank=True, help_text='Comma-separated: flatbed,rollback,heavy-duty', max_length=255)),
                ('availability', models.CharField(choices=[('actively_hunting', 'Actively Hunting'), ('employed_open', 'Employed but Open'), ('not_looking', 'Not Looking')], default='actively_hunting', max_length=20)),
                ('min_pay_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preferred_shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('rotating', 'Rotating'), ('flexible', 'Flexible')], default='flexible', max_length=10)),
                ('willing_relocate', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('last_employer', models.CharField(blank=True, max_length=200)),
                ('equipment_experience', models.CharField(blank=True, max_length=255)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sms_profile_views', models.BooleanField(default=True)),
                ('sms_interview_req', models.BooleanField(default=True)),
                ('sms_private_offer', models.BooleanField(default=True)),
                ('sms_job_match', models.BooleanField(default=True)),
                ('alert_cdl_expiry', models.BooleanField(default=True)),
                ('alert_dot_expiry', models.BooleanField(default=True)),
                ('alert_mvr_annual', models.BooleanField(default=True)),
                ('alert_wreckmaster', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pools.citypool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reliability', models.PositiveSmallIntegerField(default=5)),
                ('punctuality', models.PositiveSmallIntegerField(default=5)),
                ('equipment', models.PositiveSmallIntegerField(default=5)),
                ('communication', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('employed_from', models.DateField(blank=True, null=True)),
                ('employed_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='companies.companyprofile')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='drivers.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('cdl', 'CDL'), ('dot_medical', 'DOT Medical Card'), ('mvr', 'MVR (Motor Vehicle Record)'), ('drug_test', 'Drug Test'), ('wreckmaster', 'WreckMaster Certification'), ('hazmat', 'Hazmat Endorsement'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Review'), ('expired', 'Expired'), ('missing', 'Not Uploaded')], default='missing', max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='drivers.driverprofile')),
            ],
            options={
                'unique_together': {('driver', 'credential_type')},
            },
        ),
    ]
