# Generated by Django 4.1.2 on 2026-03-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driverdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='credentials/'),
        ),
    ]
