# Generated by Django 4.1.2 on 2026-03-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_credential_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
