# Generated by Django 4.1.2 on 2026-03-17 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('towing', 'Towing'), ('freight', 'Freight / Box Truck'), ('both', 'Both')], default='both', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('years_in_operation', models.PositiveIntegerField(default=0)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text Message')], default='email', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pools.citypool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
