# Generated by Django 4.1.2 on 2026-03-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_credential_file'),
        ('companies', '0002_credentialaccessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionalism', models.PositiveSmallIntegerField(default=5)),
                ('communication', models.PositiveSmallIntegerField(default=5)),
                ('pay_reliability', models.PositiveSmallIntegerField(default=5)),
                ('equipment_quality', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='companies.companyprofile')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_left_for_companies', to='drivers.driverprofile')),
            ],
        ),
    ]
