# Generated by Django 4.1.2 on 2026-03-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialaccessrequest',
            name='credential_type',
            field=models.CharField(default='all', max_length=20),
        ),
    ]
